# .github/workflows/azure-static-web-apps.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Step 2: Setup .NET Core
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.402

      # Step 3: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0  # Specify the Node.js version

      # Step 4: Install dependencies for frontend (React app)
      - name: Install dependencies for frontend
        working-directory: ./mksite.client
        run: npm install

      # Step 5: Build the React app
      - name: Build frontend
        working-directory: ./mksite.client
        run: npm run build

      # Step 6: Publish the .NET backend
      - name: Publish backend API
        working-directory: ./mksite.Server
        run: dotnet publish -c Release -o ./output

      # Step 7: Deploy to Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (PR comments, etc.)
          action: "upload"
          app_location: "./mksite.client"          # React app source code path
          api_location: "./mksite.Server"   # .NET backend publish output path
          output_location: "./dist"  # Built app content directory (output of `npm run build`)
